FAQs
HelpAPaw/Flutter pull request #28
Opened 2023-05-21 12:46 UTC by johnykoudsy

2023-05-21 14:05 UTC, ehsankkk1 requested changes
Very good only one small change

2023-05-21 14:05 UTC, ehsankkk1 commented on lib/presentation/faqs/faqs.dart
Replace SingleChildScrollView with ListView with padding property inside please

2023-05-21 14:18 UTC, ehsankkk1 approved these changes

2023-06-13 22:42 UTC, AbdhilahiRahimWabwire approved these changes

2023-06-13 22:42 UTC, merged